/**
 * Generates src/data/erpData.ts with realistic coherent mock data.
 * Run: node scripts/generateErpData.mjs
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const outPath = path.join(__dirname, '..', 'src', 'data', 'erpData.ts')

const typesBlock = `// Keiros ERP - mock data for development screens
// Generated by scripts/generateErpData.mjs - re-run to refresh.
// Types / entity map: see ./schema.ts and ./entityMap.ts

export * from './schema'
import type {
  Complex,
  SiteProperty,
  Organization,
  User,
  Role,
  Building,
  Floor,
  MapLocation,
  MappingQueueItem,
  QualityIssue,
  Approval,
  Correction,
  MapVersion,
  Route,
  PropertyCode,
  CodeUsage,
  MapDownload,
  MobileSession,
  Journey,
  DwellMetric,
  Tour,
  TenantActivity,
  ApiClient,
  ApiKey,
  ApiUsageStat,
  ApiLog,
  Alert,
  AuditLog,
  SystemHealthService,
} from './schema'
`

function j(v) {
  return JSON.stringify(v)
}

function locId(n) {
  return `loc-${String(n).padStart(3, '0')}`
}

/** @type {Array<{id:string,buildingId:string,buildingName:string,complexId:string|null,complexName:string|null,label:string,level:number,mappedPct:number,address:string,lat:number,lng:number,elev:number,prefix:string,rooms:Array<{name:string,type:string,code:string,mapped?:boolean}>}>} */
const floorSpecs = []

function addFloor(spec) {
  floorSpecs.push(spec)
}

function gridRooms(items, cols = 4) {
  return items.map((item, i) => ({
    ...item,
    ox: ((i % cols) - (cols - 1) / 2) * 0.00011,
    oy: (Math.floor(i / cols) - 1) * 0.00009,
  }))
}

// --- Orion Complex (Chicago) ---
const orionAddr = '1200 N Michigan Ave, Chicago, IL'
addFloor({
  id: 'flr-001', buildingId: 'bld-001', buildingName: 'North Tower', complexId: 'cpx-001', complexName: 'Orion Complex',
  label: 'L22', level: 22, mappedPct: 100, address: orionAddr, lat: 41.8954, lng: -87.6243, elev: 252.4, prefix: 'OC-NT-L22',
  rooms: gridRooms([
    { name: 'Suite 2201', type: 'Unit', code: '2201' },
    { name: 'Suite 2208', type: 'Unit', code: '2208' },
    { name: 'Suite 2212', type: 'Unit', code: '2212' },
    { name: 'Conf Room A', type: 'Room', code: 'CRA' },
    { name: 'Conf Room B', type: 'Room', code: 'CRB' },
    { name: 'Pantry 22', type: 'Amenity', code: 'PNY' },
    { name: 'Corridor B', type: 'Corridor', code: 'CB' },
    { name: 'Elevator Bank A', type: 'Elevator', code: 'ELA' },
    { name: 'Stairs North', type: 'Stairs', code: 'STN' },
    { name: 'Copy Center', type: 'Amenity', code: 'CPY' },
  ]),
})
addFloor({
  id: 'flr-002', buildingId: 'bld-001', buildingName: 'North Tower', complexId: 'cpx-001', complexName: 'Orion Complex',
  label: 'L21', level: 21, mappedPct: 100, address: orionAddr, lat: 41.89542, lng: -87.62432, elev: 249.2, prefix: 'OC-NT-L21',
  rooms: gridRooms([
    { name: 'Suite 2104', type: 'Unit', code: '2104' },
    { name: 'Suite 2110', type: 'Unit', code: '2110' },
    { name: 'Open Desk Zone', type: 'Room', code: 'ODZ' },
    { name: 'Corridor A', type: 'Corridor', code: 'CA' },
    { name: 'Elevator Bank A', type: 'Elevator', code: 'ELA' },
    { name: 'Restroom 21W', type: 'Amenity', code: 'RRW' },
    { name: 'IT Closet', type: 'Room', code: 'ITC' },
    { name: 'Stairs North', type: 'Stairs', code: 'STN' },
  ]),
})
addFloor({
  id: 'flr-003', buildingId: 'bld-001', buildingName: 'North Tower', complexId: 'cpx-001', complexName: 'Orion Complex',
  label: 'L01', level: 1, mappedPct: 98, address: orionAddr, lat: 41.89564, lng: -87.62412, elev: 185.2, prefix: 'OC-NT-L01',
  rooms: gridRooms([
    { name: 'Main Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'Main Entry', type: 'Entry', code: 'ENT' },
    { name: 'Security Desk', type: 'Amenity', code: 'SEC' },
    { name: 'Elevator Bank A', type: 'Elevator', code: 'ELA' },
    { name: 'Visitor Waiting', type: 'Room', code: 'VWT' },
    { name: 'Loading Exit', type: 'Exit', code: 'EXT' },
    { name: 'Stairs North', type: 'Stairs', code: 'STN' },
    { name: 'Mail Room', type: 'Room', code: 'MAIL' },
    { name: 'Corridor Lobby', type: 'Corridor', code: 'CLB' },
  ]),
})
addFloor({
  id: 'flr-013', buildingId: 'bld-001', buildingName: 'North Tower', complexId: 'cpx-001', complexName: 'Orion Complex',
  label: 'L10', level: 10, mappedPct: 96, address: orionAddr, lat: 41.89545, lng: -87.62428, elev: 214.0, prefix: 'OC-NT-L10',
  rooms: gridRooms([
    { name: 'Suite 1002', type: 'Unit', code: '1002' },
    { name: 'Suite 1008', type: 'Unit', code: '1008' },
    { name: 'Training Room', type: 'Room', code: 'TRN' },
    { name: 'Elevator Bank A', type: 'Elevator', code: 'ELA' },
    { name: 'Pantry 10', type: 'Amenity', code: 'PNY' },
    { name: 'Corridor C', type: 'Corridor', code: 'CC' },
  ]),
})
addFloor({
  id: 'flr-011', buildingId: 'bld-002', buildingName: 'South Tower', complexId: 'cpx-001', complexName: 'Orion Complex',
  label: 'L01', level: 1, mappedPct: 94, address: orionAddr, lat: 41.8949, lng: -87.62415, elev: 185.2, prefix: 'OC-ST-L01',
  rooms: gridRooms([
    { name: 'South Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'South Entry', type: 'Entry', code: 'ENT' },
    { name: 'Cafe Orion', type: 'Amenity', code: 'CFE' },
    { name: 'Elevator Bank B', type: 'Elevator', code: 'ELB' },
    { name: 'Bike Storage', type: 'Parking', code: 'BIK' },
    { name: 'Stairs South', type: 'Stairs', code: 'STS' },
  ]),
})
addFloor({
  id: 'flr-014', buildingId: 'bld-002', buildingName: 'South Tower', complexId: 'cpx-001', complexName: 'Orion Complex',
  label: 'L08', level: 8, mappedPct: 90, address: orionAddr, lat: 41.89488, lng: -87.6242, elev: 208.5, prefix: 'OC-ST-L08',
  rooms: gridRooms([
    { name: 'Suite 802', type: 'Unit', code: '802' },
    { name: 'Suite 810', type: 'Unit', code: '810' },
    { name: 'Board Room S', type: 'Room', code: 'BRS' },
    { name: 'Elevator Bank B', type: 'Elevator', code: 'ELB' },
    { name: 'Corridor S', type: 'Corridor', code: 'CS' },
    { name: 'Restroom 8E', type: 'Amenity', code: 'RRE' },
  ]),
})
addFloor({
  id: 'flr-015', buildingId: 'bld-002', buildingName: 'South Tower', complexId: 'cpx-001', complexName: 'Orion Complex',
  label: 'L16', level: 16, mappedPct: 88, address: orionAddr, lat: 41.89486, lng: -87.62422, elev: 236.0, prefix: 'OC-ST-L16',
  rooms: gridRooms([
    { name: 'Suite 1601', type: 'Unit', code: '1601' },
    { name: 'Suite 1605', type: 'Unit', code: '1605' },
    { name: 'Sky Lounge', type: 'Amenity', code: 'SKY' },
    { name: 'Elevator Bank B', type: 'Elevator', code: 'ELB' },
    { name: 'Terrace Door', type: 'Door', code: 'TRD' },
  ]),
})

// --- Harbor Mall (Boston) ---
const harborAddr = '88 Seaport Blvd, Boston, MA'
addFloor({
  id: 'flr-004', buildingId: 'bld-003', buildingName: 'Main Retail Block', complexId: 'cpx-002', complexName: 'Harbor Mall Campus',
  label: 'L02', level: 2, mappedPct: 86, address: harborAddr, lat: 42.3518, lng: -71.0445, elev: 12.4, prefix: 'HMC-MRB-L02',
  rooms: gridRooms([
    { name: 'Anchor Store 204', type: 'Unit', code: '204', mapped: false },
    { name: 'Boutique 210', type: 'Unit', code: '210' },
    { name: 'Boutique 218', type: 'Unit', code: '218' },
    { name: 'Restroom North', type: 'Amenity', code: 'RRN' },
    { name: 'Escalator Up', type: 'Stairs', code: 'ESC' },
    { name: 'Corridor East', type: 'Corridor', code: 'CE' },
    { name: 'Kiosk Row', type: 'Amenity', code: 'KSK' },
    { name: 'Service Elevator', type: 'Elevator', code: 'SEL' },
  ], 4),
})
addFloor({
  id: 'flr-005', buildingId: 'bld-003', buildingName: 'Main Retail Block', complexId: 'cpx-002', complexName: 'Harbor Mall Campus',
  label: 'L01', level: 1, mappedPct: 94, address: harborAddr, lat: 42.3517, lng: -71.0444, elev: 9.2, prefix: 'HMC-MRB-L01',
  rooms: gridRooms([
    { name: 'Food Court', type: 'Amenity', code: 'FC' },
    { name: 'Parking Garage P1', type: 'Parking', code: 'P1' },
    { name: 'Mall Entry West', type: 'Entry', code: 'ENTW' },
    { name: 'Mall Entry East', type: 'Entry', code: 'ENTE' },
    { name: 'Guest Services', type: 'Lobby', code: 'GS' },
    { name: 'Escalator Down', type: 'Stairs', code: 'ESD' },
    { name: 'Store 108', type: 'Unit', code: '108' },
    { name: 'Store 116', type: 'Unit', code: '116' },
    { name: 'Corridor Plaza', type: 'Corridor', code: 'CP' },
  ]),
})
addFloor({
  id: 'flr-016', buildingId: 'bld-003', buildingName: 'Main Retail Block', complexId: 'cpx-002', complexName: 'Harbor Mall Campus',
  label: 'L03', level: 3, mappedPct: 72, address: harborAddr, lat: 42.35185, lng: -71.04455, elev: 15.8, prefix: 'HMC-MRB-L03',
  rooms: gridRooms([
    { name: 'Cinema Lobby', type: 'Lobby', code: 'CIN' },
    { name: 'Theater 1', type: 'Room', code: 'TH1' },
    { name: 'Theater 2', type: 'Room', code: 'TH2' },
    { name: 'Concession', type: 'Amenity', code: 'CON' },
    { name: 'Elevator C', type: 'Elevator', code: 'ELC' },
    { name: 'Exit to Roof Deck', type: 'Exit', code: 'EXT' },
  ]),
})
addFloor({
  id: 'flr-017', buildingId: 'bld-003', buildingName: 'Main Retail Block', complexId: 'cpx-002', complexName: 'Harbor Mall Campus',
  label: 'L04', level: 4, mappedPct: 60, address: harborAddr, lat: 42.3519, lng: -71.0446, elev: 19.0, prefix: 'HMC-MRB-L04',
  rooms: gridRooms([
    { name: 'Office Suite 401', type: 'Unit', code: '401', mapped: false },
    { name: 'Office Suite 408', type: 'Unit', code: '408', mapped: false },
    { name: 'Mech Room', type: 'Room', code: 'MECH' },
    { name: 'Stairs Roof', type: 'Stairs', code: 'STR' },
  ]),
})

// --- Summit Medical (Denver) ---
const summitAddr = '2550 E 17th Ave, Denver, CO'
addFloor({
  id: 'flr-006', buildingId: 'bld-004', buildingName: 'Patient Wing A', complexId: 'cpx-004', complexName: 'Summit Medical Campus',
  label: 'L03', level: 3, mappedPct: 100, address: summitAddr, lat: 39.74346, lng: -104.9556, elev: 1619.6, prefix: 'SMC-PWA-L03',
  rooms: gridRooms([
    { name: 'Radiology', type: 'Room', code: 'RAD' },
    { name: 'MRI Suite', type: 'Room', code: 'MRI' },
    { name: 'Waiting Area A', type: 'Amenity', code: 'WTA' },
    { name: 'Staff Exit', type: 'Exit', code: 'EXT' },
    { name: 'Elevator Med A', type: 'Elevator', code: 'ELA' },
    { name: 'Corridor Imaging', type: 'Corridor', code: 'CIM' },
    { name: 'Nurses Station A', type: 'Room', code: 'NSA' },
    { name: 'Exam 301', type: 'Room', code: '301' },
  ]),
})
addFloor({
  id: 'flr-018', buildingId: 'bld-004', buildingName: 'Patient Wing A', complexId: 'cpx-004', complexName: 'Summit Medical Campus',
  label: 'L01', level: 1, mappedPct: 100, address: summitAddr, lat: 39.7435, lng: -104.95555, elev: 1612.0, prefix: 'SMC-PWA-L01',
  rooms: gridRooms([
    { name: 'Main Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'ER Entry', type: 'Entry', code: 'ER' },
    { name: 'Triage', type: 'Room', code: 'TRG' },
    { name: 'Pharmacy', type: 'Amenity', code: 'PHM' },
    { name: 'Elevator Med A', type: 'Elevator', code: 'ELA' },
    { name: 'Ambulance Bay', type: 'Parking', code: 'AMB' },
  ]),
})
addFloor({
  id: 'flr-019', buildingId: 'bld-004', buildingName: 'Patient Wing A', complexId: 'cpx-004', complexName: 'Summit Medical Campus',
  label: 'L02', level: 2, mappedPct: 97, address: summitAddr, lat: 39.74348, lng: -104.95558, elev: 1615.8, prefix: 'SMC-PWA-L02',
  rooms: gridRooms([
    { name: 'Lab Draw', type: 'Room', code: 'LAB' },
    { name: 'Infusion Bay', type: 'Room', code: 'INF' },
    { name: 'Waiting Area B', type: 'Amenity', code: 'WTB' },
    { name: 'Elevator Med A', type: 'Elevator', code: 'ELA' },
    { name: 'Corridor Clinic', type: 'Corridor', code: 'CCL' },
  ]),
})
addFloor({
  id: 'flr-012', buildingId: 'bld-005', buildingName: 'Patient Wing B', complexId: 'cpx-004', complexName: 'Summit Medical Campus',
  label: 'L03', level: 3, mappedPct: 92, address: summitAddr, lat: 39.7429, lng: -104.9551, elev: 1619.6, prefix: 'SMC-PWB-L03',
  rooms: gridRooms([
    { name: 'Wing B Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'Exam 312', type: 'Room', code: '312' },
    { name: 'Exam 318', type: 'Room', code: '318' },
    { name: 'Procedure 3', type: 'Room', code: 'PR3' },
    { name: 'Elevator Med B', type: 'Elevator', code: 'ELB' },
    { name: 'Stairs B', type: 'Stairs', code: 'STB' },
  ]),
})
addFloor({
  id: 'flr-020', buildingId: 'bld-005', buildingName: 'Patient Wing B', complexId: 'cpx-004', complexName: 'Summit Medical Campus',
  label: 'L01', level: 1, mappedPct: 88, address: summitAddr, lat: 39.74295, lng: -104.95505, elev: 1612.0, prefix: 'SMC-PWB-L01',
  rooms: gridRooms([
    { name: 'Wing B Entry', type: 'Entry', code: 'ENT' },
    { name: 'Registration', type: 'Lobby', code: 'REG' },
    { name: 'Cafe Summit', type: 'Amenity', code: 'CFE' },
    { name: 'Elevator Med B', type: 'Elevator', code: 'ELB' },
    { name: 'Visitor Parking B', type: 'Parking', code: 'PRK' },
  ]),
})

// --- Northgate Plaza (Seattle) ---
const ngAddr = '401 NE Northgate Way, Seattle, WA'
addFloor({
  id: 'flr-007', buildingId: 'bld-006', buildingName: 'Retail Podium', complexId: 'cpx-005', complexName: 'Northgate Plaza',
  label: 'L04', level: 4, mappedPct: 100, address: ngAddr, lat: 47.7092, lng: -122.32692, elev: 102.8, prefix: 'NG-RP-L04',
  rooms: gridRooms([
    { name: 'Unit 412', type: 'Unit', code: '412' },
    { name: 'Unit 418', type: 'Unit', code: '418' },
    { name: 'Blue Finch Cafe', type: 'Amenity', code: 'BFC' },
    { name: 'Corridor 4', type: 'Corridor', code: 'C4' },
    { name: 'Elevator Podium', type: 'Elevator', code: 'ELP' },
    { name: 'Stairs 4', type: 'Stairs', code: 'ST4' },
  ]),
})
addFloor({
  id: 'flr-021', buildingId: 'bld-006', buildingName: 'Retail Podium', complexId: 'cpx-005', complexName: 'Northgate Plaza',
  label: 'L01', level: 1, mappedPct: 100, address: ngAddr, lat: 47.70915, lng: -122.32685, elev: 92.0, prefix: 'NG-RP-L01',
  rooms: gridRooms([
    { name: 'Atrium', type: 'Lobby', code: 'ATR' },
    { name: 'Plaza Entry', type: 'Entry', code: 'ENT' },
    { name: 'Unit 104', type: 'Unit', code: '104' },
    { name: 'Unit 110', type: 'Unit', code: '110' },
    { name: 'Elevator Podium', type: 'Elevator', code: 'ELP' },
    { name: 'Parking Entrance', type: 'Parking', code: 'PRK' },
  ]),
})
addFloor({
  id: 'flr-022', buildingId: 'bld-006', buildingName: 'Retail Podium', complexId: 'cpx-005', complexName: 'Northgate Plaza',
  label: 'L02', level: 2, mappedPct: 95, address: ngAddr, lat: 47.70918, lng: -122.32688, elev: 95.6, prefix: 'NG-RP-L02',
  rooms: gridRooms([
    { name: 'Unit 208', type: 'Unit', code: '208' },
    { name: 'Unit 214', type: 'Unit', code: '214' },
    { name: 'Shared Kitchen', type: 'Amenity', code: 'KIT' },
    { name: 'Elevator Podium', type: 'Elevator', code: 'ELP' },
  ]),
})
addFloor({
  id: 'flr-023', buildingId: 'bld-006', buildingName: 'Retail Podium', complexId: 'cpx-005', complexName: 'Northgate Plaza',
  label: 'L03', level: 3, mappedPct: 90, address: ngAddr, lat: 47.70919, lng: -122.3269, elev: 99.2, prefix: 'NG-RP-L03',
  rooms: gridRooms([
    { name: 'Unit 302', type: 'Unit', code: '302' },
    { name: 'Unit 310', type: 'Unit', code: '310' },
    { name: 'Meeting Pod', type: 'Room', code: 'POD' },
    { name: 'Elevator Podium', type: 'Elevator', code: 'ELP' },
  ]),
})

// --- Lakeside Community (Austin) ---
const lakeAddr = '4100 Lakeshore Dr, Austin, TX'
addFloor({
  id: 'flr-008', buildingId: 'bld-007', buildingName: 'Lakeside Building A', complexId: 'cpx-003', complexName: 'Lakeside Community',
  label: 'L03', level: 3, mappedPct: 55, address: lakeAddr, lat: 30.30725, lng: -97.7557, elev: 169.6, prefix: 'LC-LBA-L03',
  rooms: gridRooms([
    { name: 'Community Pool', type: 'Pool', code: 'POOL', mapped: false },
    { name: 'Fitness Center', type: 'Gym', code: 'GYM', mapped: false },
    { name: 'Club Lounge', type: 'Amenity', code: 'CLB', mapped: false },
    { name: 'Unit A301', type: 'Unit', code: 'A301', mapped: false },
    { name: 'Unit A308', type: 'Unit', code: 'A308' },
    { name: 'Stairs A', type: 'Stairs', code: 'STA' },
  ]),
})
addFloor({
  id: 'flr-024', buildingId: 'bld-007', buildingName: 'Lakeside Building A', complexId: 'cpx-003', complexName: 'Lakeside Community',
  label: 'L01', level: 1, mappedPct: 70, address: lakeAddr, lat: 30.3072, lng: -97.75565, elev: 162.0, prefix: 'LC-LBA-L01',
  rooms: gridRooms([
    { name: 'Building A Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'Resident Entry', type: 'Entry', code: 'ENT' },
    { name: 'Mail Center', type: 'Amenity', code: 'MAIL' },
    { name: 'Unit A101', type: 'Unit', code: 'A101' },
    { name: 'Unit A110', type: 'Unit', code: 'A110', mapped: false },
  ]),
})
addFloor({
  id: 'flr-025', buildingId: 'bld-009', buildingName: 'Lakeside Building B', complexId: 'cpx-003', complexName: 'Lakeside Community',
  label: 'L02', level: 2, mappedPct: 40, address: lakeAddr, lat: 30.3069, lng: -97.7552, elev: 165.5, prefix: 'LC-LBB-L02',
  rooms: gridRooms([
    { name: 'Unit B204', type: 'Unit', code: 'B204', mapped: false },
    { name: 'Unit B212', type: 'Unit', code: 'B212', mapped: false },
    { name: 'Corridor B', type: 'Corridor', code: 'CB', mapped: false },
    { name: 'Elevator B', type: 'Elevator', code: 'ELB' },
  ]),
})
addFloor({
  id: 'flr-026', buildingId: 'bld-010', buildingName: 'Lakeside Building C', complexId: 'cpx-003', complexName: 'Lakeside Community',
  label: 'L01', level: 1, mappedPct: 35, address: lakeAddr, lat: 30.3075, lng: -97.7561, elev: 162.0, prefix: 'LC-LBC-L01',
  rooms: gridRooms([
    { name: 'Building C Lobby', type: 'Lobby', code: 'LBY', mapped: false },
    { name: 'Unit C102', type: 'Unit', code: 'C102', mapped: false },
    { name: 'Leasing Office', type: 'Room', code: 'LSE' },
  ]),
})

// --- Civic Center Annex (Portland) ---
const civicAddr = '1221 SW 4th Ave, Portland, OR'
addFloor({
  id: 'flr-027', buildingId: 'bld-008', buildingName: 'Civic Wing East', complexId: 'cpx-006', complexName: 'Civic Center Annex',
  label: 'L01', level: 1, mappedPct: 80, address: civicAddr, lat: 45.5152, lng: -122.6784, elev: 18.0, prefix: 'CCA-CWE-L01',
  rooms: gridRooms([
    { name: 'Main Entry', type: 'Entry', code: 'ENT' },
    { name: 'Public Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'Security Screening', type: 'Amenity', code: 'SEC' },
    { name: 'Elevator East', type: 'Elevator', code: 'ELE' },
    { name: 'Info Desk', type: 'Amenity', code: 'INF' },
  ]),
})
addFloor({
  id: 'flr-028', buildingId: 'bld-008', buildingName: 'Civic Wing East', complexId: 'cpx-006', complexName: 'Civic Center Annex',
  label: 'L05', level: 5, mappedPct: 65, address: civicAddr, lat: 45.51525, lng: -122.67835, elev: 34.0, prefix: 'CCA-CWE-L05',
  rooms: gridRooms([
    { name: 'Council Chamber', type: 'Room', code: 'CCL' },
    { name: 'Gallery', type: 'Room', code: 'GAL' },
    { name: 'Press Room', type: 'Room', code: 'PRS' },
    { name: 'Elevator East', type: 'Elevator', code: 'ELE' },
    { name: 'Stairs East', type: 'Stairs', code: 'STE' },
  ]),
})
addFloor({
  id: 'flr-029', buildingId: 'bld-011', buildingName: 'Civic Wing West', complexId: 'cpx-006', complexName: 'Civic Center Annex',
  label: 'L02', level: 2, mappedPct: 70, address: civicAddr, lat: 45.51505, lng: -122.6789, elev: 22.0, prefix: 'CCA-CWW-L02',
  rooms: gridRooms([
    { name: 'Permit Counter', type: 'Room', code: 'PRM' },
    { name: 'Waiting Hall', type: 'Amenity', code: 'WTH' },
    { name: 'West Entry', type: 'Entry', code: 'ENT' },
    { name: 'Elevator West', type: 'Elevator', code: 'ELW' },
  ]),
})
addFloor({
  id: 'flr-030', buildingId: 'bld-011', buildingName: 'Civic Wing West', complexId: 'cpx-006', complexName: 'Civic Center Annex',
  label: 'L03', level: 3, mappedPct: 58, address: civicAddr, lat: 45.51508, lng: -122.67888, elev: 26.0, prefix: 'CCA-CWW-L03',
  rooms: gridRooms([
    { name: 'Hearing Room 3', type: 'Room', code: 'HR3' },
    { name: 'Staff Corridor', type: 'Corridor', code: 'SC' },
    { name: 'Elevator West', type: 'Elevator', code: 'ELW' },
  ]),
})

// --- Meridian Residences (Miami) ---
const merAddr = '900 Brickell Bay Dr, Miami, FL'
addFloor({
  id: 'flr-031', buildingId: 'bld-012', buildingName: 'Meridian Tower 1', complexId: 'cpx-007', complexName: 'Meridian Residences',
  label: 'L01', level: 1, mappedPct: 85, address: merAddr, lat: 25.7640, lng: -80.1900, elev: 4.0, prefix: 'MR-T1-L01',
  rooms: gridRooms([
    { name: 'Tower 1 Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'Porte Cochere', type: 'Entry', code: 'ENT' },
    { name: 'Concierge', type: 'Amenity', code: 'CON' },
    { name: 'Elevator T1', type: 'Elevator', code: 'ELT' },
    { name: 'Valet Desk', type: 'Parking', code: 'VAL' },
  ]),
})
addFloor({
  id: 'flr-032', buildingId: 'bld-012', buildingName: 'Meridian Tower 1', complexId: 'cpx-007', complexName: 'Meridian Residences',
  label: 'L14', level: 14, mappedPct: 92, address: merAddr, lat: 25.76405, lng: -80.19005, elev: 48.0, prefix: 'MR-T1-L14',
  rooms: gridRooms([
    { name: 'Residence 1402', type: 'Unit', code: '1402' },
    { name: 'Residence 1408', type: 'Unit', code: '1408' },
    { name: 'Residence 1415', type: 'Unit', code: '1415' },
    { name: 'Corridor 14', type: 'Corridor', code: 'C14' },
    { name: 'Elevator T1', type: 'Elevator', code: 'ELT' },
    { name: 'Trash Room', type: 'Amenity', code: 'TRH' },
  ]),
})
addFloor({
  id: 'flr-033', buildingId: 'bld-013', buildingName: 'Meridian Tower 2', complexId: 'cpx-007', complexName: 'Meridian Residences',
  label: 'L01', level: 1, mappedPct: 80, address: merAddr, lat: 25.7637, lng: -80.1897, elev: 4.0, prefix: 'MR-T2-L01',
  rooms: gridRooms([
    { name: 'Tower 2 Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'Tower 2 Entry', type: 'Entry', code: 'ENT' },
    { name: 'Elevator T2', type: 'Elevator', code: 'ELT' },
  ]),
})
addFloor({
  id: 'flr-034', buildingId: 'bld-014', buildingName: 'Meridian Amenity Pavilion', complexId: 'cpx-007', complexName: 'Meridian Residences',
  label: 'L02', level: 2, mappedPct: 75, address: merAddr, lat: 25.76385, lng: -80.18985, elev: 8.5, prefix: 'MR-AP-L02',
  rooms: gridRooms([
    { name: 'Amenity Level Pool', type: 'Pool', code: 'POOL' },
    { name: 'Fitness Studio', type: 'Gym', code: 'GYM' },
    { name: 'Resident Lounge', type: 'Amenity', code: 'LNG' },
    { name: 'Sky Deck Door', type: 'Door', code: 'DK' },
  ]),
})
addFloor({
  id: 'flr-035', buildingId: 'bld-015', buildingName: 'Meridian Tower 3', complexId: 'cpx-007', complexName: 'Meridian Residences',
  label: 'L08', level: 8, mappedPct: 70, address: merAddr, lat: 25.7642, lng: -80.1903, elev: 30.0, prefix: 'MR-T3-L08',
  rooms: gridRooms([
    { name: 'Residence 802', type: 'Unit', code: '802' },
    { name: 'Residence 810', type: 'Unit', code: '810' },
    { name: 'Elevator T3', type: 'Elevator', code: 'ELT' },
    { name: 'Corridor 8', type: 'Corridor', code: 'C8' },
  ]),
})

// --- Independents ---
const clinicAddr = '220 Clinic Park Dr, San Jose, CA'
addFloor({
  id: 'flr-009', buildingId: 'bld-ind-001', buildingName: 'Standalone Clinic', complexId: null, complexName: null,
  label: 'L01', level: 1, mappedPct: 100, address: clinicAddr, lat: 37.33844, lng: -121.88621, elev: 28.2, prefix: 'SC-L01',
  rooms: gridRooms([
    { name: 'Reception Door', type: 'Door', code: 'D01' },
    { name: 'Reception Desk', type: 'Lobby', code: 'RCP' },
    { name: 'Exam 1', type: 'Room', code: 'EX1' },
    { name: 'Exam 2', type: 'Room', code: 'EX2' },
    { name: 'Lab', type: 'Room', code: 'LAB' },
    { name: 'Patient Exit', type: 'Exit', code: 'EXT' },
  ]),
})
addFloor({
  id: 'flr-036', buildingId: 'bld-ind-001', buildingName: 'Standalone Clinic', complexId: null, complexName: null,
  label: 'L02', level: 2, mappedPct: 100, address: clinicAddr, lat: 37.33846, lng: -121.88618, elev: 32.0, prefix: 'SC-L02',
  rooms: gridRooms([
    { name: 'Admin Office', type: 'Room', code: 'ADM' },
    { name: 'Conference', type: 'Room', code: 'CNF' },
    { name: 'Stairs Clinic', type: 'Stairs', code: 'ST' },
  ]),
})

const riverAddr = '88 Embarcadero, San Francisco, CA'
addFloor({
  id: 'flr-010', buildingId: 'bld-ind-002', buildingName: 'Riverside Tower', complexId: null, complexName: null,
  label: 'L08', level: 8, mappedPct: 90, address: riverAddr, lat: 37.7950, lng: -122.3997, elev: 37.6, prefix: 'RT-L08',
  rooms: gridRooms([
    { name: 'Executive Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'Visitor Parking', type: 'Parking', code: 'PARK' },
    { name: 'Suite 801', type: 'Unit', code: '801' },
    { name: 'Suite 812', type: 'Unit', code: '812' },
    { name: 'Elevator Core', type: 'Elevator', code: 'ELC' },
    { name: 'Boardroom', type: 'Room', code: 'BRD' },
  ]),
})
addFloor({
  id: 'flr-037', buildingId: 'bld-ind-002', buildingName: 'Riverside Tower', complexId: null, complexName: null,
  label: 'L01', level: 1, mappedPct: 95, address: riverAddr, lat: 37.79495, lng: -122.39965, elev: 5.0, prefix: 'RT-L01',
  rooms: gridRooms([
    { name: 'Street Entry', type: 'Entry', code: 'ENT' },
    { name: 'Ground Lobby', type: 'Lobby', code: 'LBY' },
    { name: 'Security', type: 'Amenity', code: 'SEC' },
    { name: 'Elevator Core', type: 'Elevator', code: 'ELC' },
  ]),
})
addFloor({
  id: 'flr-038', buildingId: 'bld-ind-002', buildingName: 'Riverside Tower', complexId: null, complexName: null,
  label: 'L12', level: 12, mappedPct: 85, address: riverAddr, lat: 37.79505, lng: -122.39972, elev: 52.0, prefix: 'RT-L12',
  rooms: gridRooms([
    { name: 'Penthouse A', type: 'Unit', code: 'PHA' },
    { name: 'Penthouse B', type: 'Unit', code: 'PHB' },
    { name: 'Terrace Door', type: 'Door', code: 'TRD' },
    { name: 'Elevator Core', type: 'Elevator', code: 'ELC' },
  ]),
})

// Build locations
const locations = []
let locN = 1
for (const floor of floorSpecs) {
  const propertyId = floor.complexId ?? floor.buildingId
  for (const room of floor.rooms) {
    const mapped = room.mapped !== false
    const lat = +(floor.lat + (room.ox || 0)).toFixed(6)
    const lng = +(floor.lng + (room.oy || 0)).toFixed(6)
    const namePart = room.name.includes(',') ? room.name : room.name
    locations.push({
      id: locId(locN++),
      floorId: floor.id,
      floorLabel: floor.label,
      buildingId: floor.buildingId,
      buildingName: floor.buildingName,
      complexId: floor.complexId,
      complexName: floor.complexName,
      propertyId,
      name: namePart,
      type: room.type,
      code: `${floor.prefix}-${room.code}`,
      mapped,
      physicalAddress: `${floor.address} Â· ${room.name}`,
      latitude: lat,
      longitude: lng,
      elevation: floor.elev,
    })
  }
}

const floors = floorSpecs.map((f) => {
  const locs = locations.filter((l) => l.floorId === f.id)
  const mapped = locs.filter((l) => l.mapped).length
  return {
    id: f.id,
    buildingId: f.buildingId,
    buildingName: f.buildingName,
    complexId: f.complexId,
    complexName: f.complexName,
    propertyId: f.complexId ?? f.buildingId,
    label: f.label,
    level: f.level,
    locations: locs.length,
    mappedPct: locs.length ? Math.round((mapped / locs.length) * 100) : f.mappedPct,
  }
})

const buildings = [
  { id: 'bld-001', complexId: 'cpx-001', complexName: 'Orion Complex', name: 'North Tower', floors: 22, mappedFloors: 4, status: 'Active', city: 'Chicago', organizationId: null },
  { id: 'bld-002', complexId: 'cpx-001', complexName: 'Orion Complex', name: 'South Tower', floors: 16, mappedFloors: 3, status: 'Active', city: 'Chicago', organizationId: null },
  { id: 'bld-003', complexId: 'cpx-002', complexName: 'Harbor Mall Campus', name: 'Main Retail Block', floors: 4, mappedFloors: 4, status: 'Active', city: 'Boston', organizationId: null },
  { id: 'bld-004', complexId: 'cpx-004', complexName: 'Summit Medical Campus', name: 'Patient Wing A', floors: 6, mappedFloors: 3, status: 'Active', city: 'Denver', organizationId: null },
  { id: 'bld-005', complexId: 'cpx-004', complexName: 'Summit Medical Campus', name: 'Patient Wing B', floors: 6, mappedFloors: 2, status: 'Active', city: 'Denver', organizationId: null },
  { id: 'bld-006', complexId: 'cpx-005', complexName: 'Northgate Plaza', name: 'Retail Podium', floors: 6, mappedFloors: 4, status: 'Active', city: 'Seattle', organizationId: null },
  { id: 'bld-007', complexId: 'cpx-003', complexName: 'Lakeside Community', name: 'Lakeside Building A', floors: 8, mappedFloors: 2, status: 'Draft', city: 'Austin', organizationId: null },
  { id: 'bld-009', complexId: 'cpx-003', complexName: 'Lakeside Community', name: 'Lakeside Building B', floors: 7, mappedFloors: 1, status: 'Draft', city: 'Austin', organizationId: null },
  { id: 'bld-010', complexId: 'cpx-003', complexName: 'Lakeside Community', name: 'Lakeside Building C', floors: 7, mappedFloors: 1, status: 'Draft', city: 'Austin', organizationId: null },
  { id: 'bld-008', complexId: 'cpx-006', complexName: 'Civic Center Annex', name: 'Civic Wing East', floors: 5, mappedFloors: 2, status: 'Active', city: 'Portland', organizationId: null },
  { id: 'bld-011', complexId: 'cpx-006', complexName: 'Civic Center Annex', name: 'Civic Wing West', floors: 4, mappedFloors: 2, status: 'Active', city: 'Portland', organizationId: null },
  { id: 'bld-012', complexId: 'cpx-007', complexName: 'Meridian Residences', name: 'Meridian Tower 1', floors: 28, mappedFloors: 2, status: 'Active', city: 'Miami', organizationId: null },
  { id: 'bld-013', complexId: 'cpx-007', complexName: 'Meridian Residences', name: 'Meridian Tower 2', floors: 24, mappedFloors: 1, status: 'Active', city: 'Miami', organizationId: null },
  { id: 'bld-014', complexId: 'cpx-007', complexName: 'Meridian Residences', name: 'Meridian Amenity Pavilion', floors: 3, mappedFloors: 1, status: 'Active', city: 'Miami', organizationId: null },
  { id: 'bld-015', complexId: 'cpx-007', complexName: 'Meridian Residences', name: 'Meridian Tower 3', floors: 22, mappedFloors: 1, status: 'Active', city: 'Miami', organizationId: null },
  { id: 'bld-ind-001', complexId: null, complexName: null, name: 'Standalone Clinic', floors: 3, mappedFloors: 2, status: 'Active', city: 'San Jose', organizationId: 'org-009' },
  { id: 'bld-ind-002', complexId: null, complexName: null, name: 'Riverside Tower', floors: 12, mappedFloors: 3, status: 'Active', city: 'San Francisco', organizationId: 'org-010' },
]

function complexStats(id) {
  const blds = buildings.filter((b) => b.complexId === id)
  const archFloors = blds.reduce((s, b) => s + b.floors, 0)
  return { buildings: blds.length, floors: archFloors }
}

const complexOrg = {
  'cpx-001': { organizationId: 'org-001', organizationName: 'Orion Property Group' },
  'cpx-002': { organizationId: 'org-002', organizationName: 'Harbor Retail Holdings' },
  'cpx-003': { organizationId: 'org-003', organizationName: 'Keiros Field Services' },
  'cpx-004': { organizationId: 'org-004', organizationName: 'Summit Health Systems' },
  'cpx-005': { organizationId: 'org-005', organizationName: 'Northgate Management Co.' },
  'cpx-006': { organizationId: 'org-008', organizationName: 'City of Portland' },
  'cpx-007': { organizationId: 'org-007', organizationName: 'Coastal Retail Partners' },
}

const complexes = [
  { id: 'cpx-001', name: 'Orion Complex', city: 'Chicago', status: 'Published', ...complexOrg['cpx-001'], ...complexStats('cpx-001'), readiness: 97, address: orionAddr },
  { id: 'cpx-002', name: 'Harbor Mall Campus', city: 'Boston', status: 'Review', ...complexOrg['cpx-002'], ...complexStats('cpx-002'), readiness: 82, address: harborAddr },
  { id: 'cpx-003', name: 'Lakeside Community', city: 'Austin', status: 'Draft', ...complexOrg['cpx-003'], ...complexStats('cpx-003'), readiness: 48, address: lakeAddr },
  { id: 'cpx-004', name: 'Summit Medical Campus', city: 'Denver', status: 'Mapped', ...complexOrg['cpx-004'], ...complexStats('cpx-004'), readiness: 93, address: summitAddr },
  { id: 'cpx-005', name: 'Northgate Plaza', city: 'Seattle', status: 'Published', ...complexOrg['cpx-005'], ...complexStats('cpx-005'), readiness: 98, address: ngAddr },
  { id: 'cpx-006', name: 'Civic Center Annex', city: 'Portland', status: 'Review', ...complexOrg['cpx-006'], ...complexStats('cpx-006'), readiness: 72, address: civicAddr },
  { id: 'cpx-007', name: 'Meridian Residences', city: 'Miami', status: 'Mapped', ...complexOrg['cpx-007'], ...complexStats('cpx-007'), readiness: 86, address: merAddr },
]

/* â”€â”€â”€ Unified SiteProperty catalog (ops join root) â”€â”€â”€ */
const independentBuildings = buildings.filter((b) => !b.complexId)
const siteProperties = [
  ...complexes.map((c) => ({
    id: c.id,
    kind: 'complex',
    name: c.name,
    city: c.city,
    organizationId: c.organizationId,
    organizationName: c.organizationName,
    status: c.status,
    complexId: c.id,
    buildingId: null,
    readiness: c.readiness,
    address: c.address,
  })),
  ...independentBuildings.map((b) => ({
    id: b.id,
    kind: 'independent',
    name: b.name,
    city: b.city,
    organizationId: b.organizationId,
    organizationName: b.organizationId === 'org-009' ? 'Bay Area Clinics LLC' : 'Embarcadero Holdings',
    status: b.status,
    complexId: null,
    buildingId: b.id,
    readiness: b.id === 'bld-ind-001' ? 91 : 64,
    address: b.id === 'bld-ind-001' ? clinicAddr : riverAddr,
  })),
]

const propertyByName = Object.fromEntries(siteProperties.map((p) => [p.name, p]))
const propertyLabels = siteProperties.map((p) => p.name)

function locsForProperty(propertyNameOrId) {
  const prop = propertyByName[propertyNameOrId] || siteProperties.find((p) => p.id === propertyNameOrId)
  if (!prop) return []
  return locations.filter((l) => l.propertyId === prop.id)
}

function floorsForProperty(propertyNameOrId) {
  const prop = propertyByName[propertyNameOrId] || siteProperties.find((p) => p.id === propertyNameOrId)
  if (!prop) return []
  return floors.filter((f) => f.propertyId === prop.id)
}

function findLoc(propertyName, name) {
  const pool = locsForProperty(propertyName)
  return (
    pool.find((l) => l.name === name) ||
    pool.find((l) => l.name.toLowerCase().includes(String(name).toLowerCase())) ||
    null
  )
}

function propertyFloorCount(propertyName) {
  const prop = propertyByName[propertyName]
  if (!prop) return floorsForProperty(propertyName).length
  if (prop.kind === 'complex') {
    const cpx = complexes.find((c) => c.id === prop.id)
    return cpx?.floors ?? floorsForProperty(propertyName).length
  }
  return independentBuildings.find((b) => b.id === prop.id)?.floors ?? floorsForProperty(propertyName).length
}

function pad(n, w = 3) {
  return String(n).padStart(w, '0')
}

function userByName(name) {
  return users.find((u) => u.name === name) || null
}

function floorByPropertyLabel(propertyName, preferred) {
  const fls = floorsForProperty(propertyName)
  if (!fls.length) return null
  return fls.find((f) => f.label === preferred) || fls[0]
}

/* â”€â”€â”€ Organizations â”€â”€â”€ */
const orgOwnership = [
  { id: 'org-001', name: 'Orion Property Group', type: 'Owner', status: 'Active', propertiesOwned: ['Orion Complex'] },
  { id: 'org-002', name: 'Harbor Retail Holdings', type: 'Owner', status: 'Active', propertiesOwned: ['Harbor Mall Campus'] },
  { id: 'org-003', name: 'Keiros Field Services', type: 'PMC', status: 'Active', propertiesOwned: ['Lakeside Community'] },
  { id: 'org-004', name: 'Summit Health Systems', type: 'Customer', status: 'Active', propertiesOwned: ['Summit Medical Campus'] },
  { id: 'org-005', name: 'Northgate Management Co.', type: 'PMC', status: 'Active', propertiesOwned: ['Northgate Plaza'] },
  { id: 'org-006', name: 'Atlas Ventures', type: 'Owner', status: 'Pending', propertiesOwned: [] },
  { id: 'org-007', name: 'Coastal Retail Partners', type: 'Customer', status: 'Active', propertiesOwned: ['Meridian Residences'] },
  { id: 'org-008', name: 'City of Portland', type: 'Customer', status: 'Active', propertiesOwned: ['Civic Center Annex'] },
  { id: 'org-009', name: 'Bay Area Clinics LLC', type: 'Owner', status: 'Active', propertiesOwned: ['Standalone Clinic'] },
  { id: 'org-010', name: 'Embarcadero Holdings', type: 'Owner', status: 'Active', propertiesOwned: ['Riverside Tower'] },
  { id: 'org-011', name: 'Keiros', type: 'PMC', status: 'Active', propertiesOwned: [] },
]

const organizations = orgOwnership.map(({ propertiesOwned, ...org }) => ({
  ...org,
  properties: propertiesOwned.length,
}))

const orgByName = Object.fromEntries(organizations.map((o) => [o.name, o]))

const roleDefs = [
  { id: 'rol-001', name: 'Platform Admin', permissions: 'all' },
  { id: 'rol-002', name: 'Property Manager', permissions: 'properties:rw, mapping:r, analytics:r' },
  { id: 'rol-003', name: 'Field Mapper', permissions: 'mapping:rw, properties:r' },
  { id: 'rol-004', name: 'QA Reviewer', permissions: 'mapping:rw, publishing:rw, properties:r' },
  { id: 'rol-005', name: 'Operations', permissions: 'analytics:r, mobile:rw, properties:r' },
  { id: 'rol-006', name: 'Viewer', permissions: 'properties:r, analytics:r' },
  { id: 'rol-007', name: 'Site Lead', permissions: 'properties:rw, mapping:r, mobile:r' },
  { id: 'rol-008', name: 'API Consumer', permissions: 'api:rw' },
]
const roleByName = Object.fromEntries(roleDefs.map((r) => [r.name, r]))

const userSeeds = [
  { id: 'usr-001', name: 'Sarah Chen', email: 'sarah.chen@keiros.ai', role: 'Platform Admin', org: 'Keiros', status: 'Active' },
  { id: 'usr-002', name: 'Marcus Webb', email: 'marcus.webb@orionpg.com', role: 'Property Manager', org: 'Orion Property Group', status: 'Active' },
  { id: 'usr-003', name: 'Elena Vasquez', email: 'elena.v@harborretail.com', role: 'Site Lead', org: 'Harbor Retail Holdings', status: 'Active' },
  { id: 'usr-004', name: 'James Okonkwo', email: 'j.okonkwo@keiros.ai', role: 'Field Mapper', org: 'Keiros Field Services', status: 'Active' },
  { id: 'usr-005', name: 'Priya Nair', email: 'priya.nair@keiros.ai', role: 'QA Reviewer', org: 'Keiros Field Services', status: 'Active' },
  { id: 'usr-006', name: 'Tom Bradley', email: 't.bradley@summithealth.org', role: 'Viewer', org: 'Summit Health Systems', status: 'Active' },
  { id: 'usr-007', name: 'Lisa Park', email: 'lisa.park@northgate.com', role: 'Operations', org: 'Northgate Management Co.', status: 'Inactive' },
  { id: 'usr-008', name: 'Devon Mills', email: 'devon.m@atlasventures.com', role: 'API Consumer', org: 'Atlas Ventures', status: 'Active' },
  { id: 'usr-009', name: 'Rita Gomez', email: 'rita.gomez@keiros.ai', role: 'Field Mapper', org: 'Keiros Field Services', status: 'Active' },
  { id: 'usr-010', name: 'Noah Kim', email: 'noah.kim@keiros.ai', role: 'Field Mapper', org: 'Keiros Field Services', status: 'Active' },
  { id: 'usr-011', name: 'Aisha Rahman', email: 'aisha.r@coastalrp.com', role: 'Property Manager', org: 'Coastal Retail Partners', status: 'Active' },
  { id: 'usr-012', name: 'Chris Delgado', email: 'c.delgado@portland.gov', role: 'Operations', org: 'City of Portland', status: 'Active' },
  { id: 'usr-013', name: 'Mei Lin', email: 'mei.lin@keiros.ai', role: 'QA Reviewer', org: 'Keiros Field Services', status: 'Active' },
  { id: 'usr-014', name: 'Jordan Blake', email: 'j.blake@bayareaclinics.com', role: 'Site Lead', org: 'Bay Area Clinics LLC', status: 'Active' },
  { id: 'usr-015', name: 'Sofia Alvarez', email: 'sofia.a@embarcadero.com', role: 'Property Manager', org: 'Embarcadero Holdings', status: 'Active' },
  { id: 'usr-016', name: 'Hank Ortega', email: 'hank.o@keiros.ai', role: 'Platform Admin', org: 'Keiros', status: 'Active' },
  { id: 'usr-017', name: 'Yuki Tanaka', email: 'yuki.t@harborretail.com', role: 'Viewer', org: 'Harbor Retail Holdings', status: 'Active' },
  { id: 'usr-018', name: 'Omar Hassan', email: 'omar.h@summithealth.org', role: 'Operations', org: 'Summit Health Systems', status: 'Inactive' },
]

const users = userSeeds.map((u) => ({
  id: u.id,
  name: u.name,
  email: u.email,
  roleId: roleByName[u.role].id,
  role: u.role,
  organizationId: orgByName[u.org].id,
  org: u.org,
  status: u.status,
}))

const roleCounts = {}
for (const u of users) roleCounts[u.role] = (roleCounts[u.role] || 0) + 1
const roles = roleDefs.map((r) => ({ ...r, usersCount: roleCounts[r.name] || 0 }))

/* â”€â”€â”€ Map versions â”€â”€â”€ */
const versionPlan = {
  'Orion Complex': { live: 'v5.1.2', prior: 'v5.0.8', status: 'Live', publishedAt: '2026-08-29' },
  'Harbor Mall Campus': { live: 'v2.4.1', prior: 'v2.3.9', status: 'Staging', publishedAt: null },
  'Lakeside Community': { live: 'v0.3.0', prior: null, status: 'Draft', publishedAt: null },
  'Summit Medical Campus': { live: 'v2.1.0', prior: 'v2.0.4', status: 'Live', publishedAt: '2026-07-20' },
  'Northgate Plaza': { live: 'v3.0.0', prior: 'v2.9.1', status: 'Live', publishedAt: '2026-08-15' },
  'Civic Center Annex': { live: 'v1.8.0', prior: 'v1.7.2', status: 'Staging', publishedAt: null },
  'Meridian Residences': { live: 'v1.2.0', prior: 'v1.1.0', status: 'Staging', publishedAt: null },
  'Standalone Clinic': { live: 'v1.0.0', prior: null, status: 'Live', publishedAt: '2026-08-10' },
  'Riverside Tower': { live: 'v0.9.1', prior: null, status: 'Draft', publishedAt: null },
}

const mapVersions = []
let mvN = 1
for (const prop of siteProperties) {
  const plan = versionPlan[prop.name]
  if (!plan) continue
  mapVersions.push({
    id: `mv-${pad(mvN++)}`,
    propertyId: prop.id,
    propertyName: prop.name,
    version: plan.live,
    status: plan.status,
    publishedAt: plan.publishedAt,
    floors: propertyFloorCount(prop.name),
  })
  if (plan.prior) {
    mapVersions.push({
      id: `mv-${pad(mvN++)}`,
      propertyId: prop.id,
      propertyName: prop.name,
      version: plan.prior,
      status: plan.status === 'Live' ? 'Archived' : 'Draft',
      publishedAt: plan.status === 'Live' ? '2026-07-01' : null,
      floors: propertyFloorCount(prop.name),
    })
  }
}

function currentVersion(propertyName) {
  const prop = propertyByName[propertyName]
  return mapVersions.find(
    (v) => v.propertyId === prop?.id && ['Live', 'Staging', 'Draft'].includes(v.status),
  )
}

function versionByPropAndLabel(propertyName, version) {
  const prop = propertyByName[propertyName]
  return mapVersions.find((v) => v.propertyId === prop?.id && v.version === version)
}

/* â”€â”€â”€ Approvals â”€â”€â”€ */
const approvalSeeds = [
  { propertyName: 'Harbor Mall Campus', version: 'v2.4.1', submittedBy: 'James Okonkwo', submittedAt: '2026-09-03 14:22', status: 'Pending' },
  { propertyName: 'Civic Center Annex', version: 'v1.8.0', submittedBy: 'Rita Gomez', submittedAt: '2026-09-02 09:15', status: 'Pending' },
  { propertyName: 'Orion Complex', version: 'v5.1.2', submittedBy: 'James Okonkwo', submittedAt: '2026-08-28 16:40', status: 'Approved' },
  { propertyName: 'Lakeside Community', version: 'v0.3.0', submittedBy: 'Rita Gomez', submittedAt: '2026-08-25 11:00', status: 'Rejected' },
  { propertyName: 'Summit Medical Campus', version: 'v2.1.0', submittedBy: 'Noah Kim', submittedAt: '2026-07-18 13:10', status: 'Approved' },
  { propertyName: 'Northgate Plaza', version: 'v3.0.0', submittedBy: 'James Okonkwo', submittedAt: '2026-08-14 10:05', status: 'Approved' },
  { propertyName: 'Meridian Residences', version: 'v1.2.0', submittedBy: 'Rita Gomez', submittedAt: '2026-09-01 16:44', status: 'Pending' },
  { propertyName: 'Harbor Mall Campus', version: 'v2.3.9', submittedBy: 'Noah Kim', submittedAt: '2026-08-20 09:30', status: 'Approved' },
  { propertyName: 'Riverside Tower', version: 'v0.9.1', submittedBy: 'Rita Gomez', submittedAt: '2026-09-03 11:18', status: 'Pending' },
  { propertyName: 'Standalone Clinic', version: 'v1.0.0', submittedBy: 'Noah Kim', submittedAt: '2026-08-10 15:00', status: 'Approved' },
]

const approvals = approvalSeeds.map((a, i) => {
  const prop = propertyByName[a.propertyName]
  const mv = versionByPropAndLabel(a.propertyName, a.version)
  const user = userByName(a.submittedBy)
  return {
    id: `ap-${pad(i + 1)}`,
    propertyId: prop.id,
    propertyName: prop.name,
    mapVersionId: mv.id,
    mapVersion: mv.version,
    submittedByUserId: user.id,
    submittedBy: user.name,
    submittedAt: a.submittedAt,
    status: a.status,
  }
})

function realFloorLabel(propertyName, preferred) {
  return floorByPropertyLabel(propertyName, preferred)?.label ?? preferred
}

const mappingQueueSeeds = [
  { propertyName: 'Harbor Mall Campus', floorLabel: 'L02', mapper: 'James Okonkwo', status: 'In Progress', priority: 1, dueDate: '2026-09-06' },
  { propertyName: 'Lakeside Community', floorLabel: 'L03', mapper: 'Unassigned', status: 'Queued', priority: 2, dueDate: '2026-09-10' },
  { propertyName: 'Civic Center Annex', floorLabel: 'L05', mapper: 'James Okonkwo', status: 'Blocked', priority: 1, dueDate: '2026-09-05' },
  { propertyName: 'Riverside Tower', floorLabel: 'L08', mapper: 'Rita Gomez', status: 'In Progress', priority: 3, dueDate: '2026-09-12' },
  { propertyName: 'Meridian Residences', floorLabel: 'L14', mapper: 'Rita Gomez', status: 'Complete', priority: 2, dueDate: '2026-09-03' },
  { propertyName: 'Harbor Mall Campus', floorLabel: 'L04', mapper: 'Noah Kim', status: 'Queued', priority: 2, dueDate: '2026-09-14' },
  { propertyName: 'Summit Medical Campus', floorLabel: 'L02', mapper: 'James Okonkwo', status: 'Complete', priority: 3, dueDate: '2026-09-01' },
  { propertyName: 'Lakeside Community', floorLabel: 'L01', mapper: 'Noah Kim', status: 'In Progress', priority: 2, dueDate: '2026-09-11' },
  { propertyName: 'Northgate Plaza', floorLabel: 'L03', mapper: 'Rita Gomez', status: 'Queued', priority: 4, dueDate: '2026-09-18' },
  { propertyName: 'Orion Complex', floorLabel: 'L01', mapper: 'James Okonkwo', status: 'Complete', priority: 3, dueDate: '2026-08-30' },
  { propertyName: 'Civic Center Annex', floorLabel: 'L02', mapper: 'Unassigned', status: 'Queued', priority: 2, dueDate: '2026-09-16' },
  { propertyName: 'Meridian Residences', floorLabel: 'L02', mapper: 'Noah Kim', status: 'In Progress', priority: 2, dueDate: '2026-09-09' },
]

const mappingQueue = mappingQueueSeeds.map((row, i) => {
  const prop = propertyByName[row.propertyName]
  const floor = floorByPropertyLabel(row.propertyName, row.floorLabel)
  const mapper = row.mapper === 'Unassigned' ? null : userByName(row.mapper)
  return {
    id: `mq-${pad(i + 1)}`,
    propertyId: prop.id,
    propertyName: prop.name,
    floorId: floor.id,
    floorLabel: floor.label,
    mapperUserId: mapper?.id ?? null,
    mapper: mapper?.name ?? 'Unassigned',
    status: row.status,
    priority: row.priority,
    dueDate: row.dueDate,
  }
})

const qualitySeeds = [
  { propertyName: 'Harbor Mall Campus', floorLabel: 'L02', issue: 'Overlapping corridor polygons', severity: 'High', reportedBy: 'Priya Nair', ageDays: 2 },
  { propertyName: 'Orion Complex', floorLabel: 'L01', issue: 'Missing elevator connection', severity: 'Medium', reportedBy: 'Priya Nair', ageDays: 5 },
  { propertyName: 'Civic Center Annex', floorLabel: 'L02', issue: 'GPS drift on entry node', severity: 'Critical', reportedBy: 'Sarah Chen', ageDays: 1 },
  { propertyName: 'Summit Medical Campus', floorLabel: 'L03', issue: 'Unit label mismatch', severity: 'Low', reportedBy: 'Mei Lin', ageDays: 8 },
  { propertyName: 'Lakeside Community', floorLabel: 'L03', issue: 'Unmapped amenity nodes', severity: 'Medium', reportedBy: 'James Okonkwo', ageDays: 3 },
  { propertyName: 'Meridian Residences', floorLabel: 'L14', issue: 'Door swing clearance short', severity: 'Low', reportedBy: 'Priya Nair', ageDays: 4 },
  { propertyName: 'Harbor Mall Campus', floorLabel: 'L01', issue: 'Parking P1 elevation offset', severity: 'High', reportedBy: 'Mei Lin', ageDays: 1 },
  { propertyName: 'Northgate Plaza', floorLabel: 'L01', issue: 'Atrium boundary incomplete', severity: 'Medium', reportedBy: 'Priya Nair', ageDays: 6 },
  { propertyName: 'Riverside Tower', floorLabel: 'L08', issue: 'Visitor parking snap error', severity: 'Low', reportedBy: 'Mei Lin', ageDays: 2 },
  { propertyName: 'Orion Complex', floorLabel: 'L22', issue: 'Suite 2212 code duplicate', severity: 'Medium', reportedBy: 'Priya Nair', ageDays: 3 },
  { propertyName: 'Summit Medical Campus', floorLabel: 'L01', issue: 'ER entry beacon timeout', severity: 'Critical', reportedBy: 'Sarah Chen', ageDays: 0 },
  { propertyName: 'Lakeside Community', floorLabel: 'L01', issue: 'Building B corridor missing', severity: 'High', reportedBy: 'James Okonkwo', ageDays: 4 },
]

const qualityIssues = qualitySeeds.map((row, i) => {
  const prop = propertyByName[row.propertyName]
  const floor = floorByPropertyLabel(row.propertyName, row.floorLabel)
  const reporter = userByName(row.reportedBy)
  return {
    id: `qi-${pad(i + 1)}`,
    propertyId: prop.id,
    propertyName: prop.name,
    floorId: floor?.id ?? null,
    floorLabel: floor?.label ?? row.floorLabel,
    issue: row.issue,
    severity: row.severity,
    reportedByUserId: reporter.id,
    reportedBy: reporter.name,
    ageDays: row.ageDays,
  }
})

const correctionSeeds = [
  { propertyName: 'Harbor Mall Campus', location: 'Anchor Store 204', description: 'Relocate unit boundary 1.2m east', assignee: 'James Okonkwo', status: 'Assigned' },
  { propertyName: 'Orion Complex', location: 'Elevator Bank A', description: 'Add floor transition node', assignee: 'James Okonkwo', status: 'Open' },
  { propertyName: 'Civic Center Annex', location: 'Main Entry', description: 'Recalibrate entry beacon', assignee: 'Rita Gomez', status: 'Open' },
  { propertyName: 'Summit Medical Campus', location: 'Radiology', description: 'Update room code prefix', assignee: 'Priya Nair', status: 'Resolved' },
  { propertyName: 'Meridian Residences', location: 'Amenity Level Pool', description: 'Capture pool deck outline', assignee: 'Noah Kim', status: 'Assigned' },
  { propertyName: 'Northgate Plaza', location: 'Atrium', description: 'Align atrium columns to survey', assignee: 'Rita Gomez', status: 'Open' },
  { propertyName: 'Lakeside Community', location: 'Fitness Center', description: 'Mark gym as mapped after resurvey', assignee: 'James Okonkwo', status: 'Assigned' },
  { propertyName: 'Orion Complex', location: 'Suite 2212', description: 'Resolve duplicate location code', assignee: 'Mei Lin', status: 'Open' },
  { propertyName: 'Harbor Mall Campus', location: 'Parking Garage P1', description: 'Correct elevation by âˆ’0.4 m', assignee: 'Noah Kim', status: 'Assigned' },
  { propertyName: 'Riverside Tower', location: 'Visitor Parking', description: 'Snap parking polygon to curb', assignee: 'Rita Gomez', status: 'Resolved' },
  { propertyName: 'Summit Medical Campus', location: 'ER Entry', description: 'Add ambulance approach node', assignee: 'James Okonkwo', status: 'Open' },
  { propertyName: 'Civic Center Annex', location: 'Council Chamber', description: 'Gallery seating labels missing', assignee: 'Priya Nair', status: 'Assigned' },
]

const corrections = correctionSeeds.map((row, i) => {
  const prop = propertyByName[row.propertyName]
  const loc = findLoc(row.propertyName, row.location)
  const assignee = userByName(row.assignee)
  if (!loc) throw new Error(`Correction location missing: ${row.propertyName} / ${row.location}`)
  return {
    id: `cr-${pad(i + 1)}`,
    propertyId: prop.id,
    propertyName: prop.name,
    locationId: loc.id,
    location: loc.name,
    description: row.description,
    assigneeUserId: assignee.id,
    assignee: assignee.name,
    status: row.status,
  }
})

/* â”€â”€â”€ Routes â”€â”€â”€ */
const routeDefs = [
  { id: 'rt-001', propertyName: 'Orion Complex', from: 'Main Lobby', to: 'Suite 2201', status: 'Active', traffic: 1.15 },
  { id: 'rt-002', propertyName: 'Harbor Mall Campus', from: 'Parking Garage P1', to: 'Food Court', status: 'Active', traffic: 1.35 },
  { id: 'rt-003', propertyName: 'Summit Medical Campus', from: 'ER Entry', to: 'Radiology', status: 'Active', traffic: 1.2 },
  { id: 'rt-004', propertyName: 'Northgate Plaza', from: 'Plaza Entry', to: 'Unit 412', status: 'Active', traffic: 1.0 },
  { id: 'rt-005', propertyName: 'Civic Center Annex', from: 'Main Entry', to: 'Council Chamber', status: 'Draft', traffic: 0.7 },
  { id: 'rt-006', propertyName: 'Orion Complex', from: 'South Entry', to: 'Suite 1601', status: 'Active', traffic: 1.05 },
  { id: 'rt-007', propertyName: 'Meridian Residences', from: 'Valet Desk', to: 'Residence 1408', status: 'Active', traffic: 1.1 },
  { id: 'rt-008', propertyName: 'Lakeside Community', from: 'Building A Lobby', to: 'Fitness Center', status: 'Draft', traffic: 0.55 },
  { id: 'rt-009', propertyName: 'Summit Medical Campus', from: 'Wing B Entry', to: 'Exam 312', status: 'Active', traffic: 1.05 },
  { id: 'rt-010', propertyName: 'Riverside Tower', from: 'Street Entry', to: 'Suite 801', status: 'Active', traffic: 0.95 },
  { id: 'rt-011', propertyName: 'Harbor Mall Campus', from: 'Mall Entry West', to: 'Cinema Lobby', status: 'Active', traffic: 1.25 },
  { id: 'rt-012', propertyName: 'Standalone Clinic', from: 'Reception Desk', to: 'Lab', status: 'Active', traffic: 0.9 },
]

function haversineM(a, b) {
  const R = 6371000
  const toRad = (d) => (d * Math.PI) / 180
  const dLat = toRad(b.latitude - a.latitude)
  const dLng = toRad(b.longitude - a.longitude)
  const lat1 = toRad(a.latitude)
  const lat2 = toRad(b.latitude)
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(h)))
}

const routeNameOverrides = {
  'rt-001': 'Lobby to Suite 2201',
  'rt-002': 'Parking to Food Court',
  'rt-003': 'ER to Radiology',
  'rt-004': 'Entry to Unit 412',
  'rt-005': 'Visitor to Council Chamber',
  'rt-006': 'South Entry to Suite 1601',
  'rt-007': 'Valet to Residence 1408',
  'rt-008': 'Lobby to Fitness Center',
  'rt-009': 'Wing B Entry to Exam 312',
  'rt-010': 'Street Entry to Suite 801',
  'rt-011': 'West Entry to Cinema Lobby',
  'rt-012': 'Reception to Lab',
}

const routes = routeDefs.map((def) => {
  const prop = propertyByName[def.propertyName]
  const from = findLoc(def.propertyName, def.from)
  const to = findLoc(def.propertyName, def.to)
  if (!from || !to) throw new Error(`Route ${def.id}: missing endpoint on ${def.propertyName}`)
  const pool = locsForProperty(def.propertyName)
  const elevators = pool.filter((l) => l.type === 'Elevator')
  const mid =
    elevators.find((e) => e.buildingId === from.buildingId || e.buildingId === to.buildingId) ||
    pool.find((l) => l.type === 'Lobby' || l.type === 'Corridor') ||
    from
  const stops = from.floorId === to.floorId ? [from, to] : [from, mid, to]
  const dist = stops.slice(1).reduce((s, stop, i) => s + haversineM(stops[i], stop), 0)
  const floorChanges = new Set(stops.map((s) => s.floorId)).size - 1
  const durationMin =
    def.status === 'Draft'
      ? 0
      : Math.round(((dist / 1.2) / 60 + Math.max(0, floorChanges) * 0.6) * 10) / 10
  return {
    id: def.id,
    propertyId: prop.id,
    propertyName: prop.name,
    name: routeNameOverrides[def.id],
    waypoints: stops.length + Math.max(0, floorChanges) * 2 + 2,
    status: def.status,
    avgDurationMin: durationMin || (def.status === 'Draft' ? 0 : 3.5),
    fromLocationId: from.id,
    toLocationId: to.id,
  }
})

/* â”€â”€â”€ Property codes + usage â”€â”€â”€ */
const codeDefs = [
  { propertyName: 'Orion Complex', code: 'OC-CHI-2026', label: 'Visitor Access', status: 'Active', expiresAt: '2027-01-01', scans: 1842 },
  { propertyName: 'Harbor Mall Campus', code: 'HM-BOS-RETAIL', label: 'Retail Staff', status: 'Active', expiresAt: null, scans: 967 },
  { propertyName: 'Summit Medical Campus', code: 'SMC-DEN-PAT', label: 'Patient Nav', status: 'Active', expiresAt: '2026-12-31', scans: 2341 },
  { propertyName: 'Northgate Plaza', code: 'NG-SEA-2025', label: 'Tenant Access', status: 'Expired', expiresAt: '2025-12-31', scans: 1540 },
  { propertyName: 'Lakeside Community', code: 'LC-AUS-PILOT', label: 'Pilot Program', status: 'Active', expiresAt: '2026-10-01', scans: 89 },
  { propertyName: 'Meridian Residences', code: 'MR-MIA-RES', label: 'Resident Access', status: 'Active', expiresAt: '2027-03-01', scans: 2210 },
  { propertyName: 'Civic Center Annex', code: 'CCA-PDX-PUB', label: 'Public Services', status: 'Active', expiresAt: null, scans: 640 },
  { propertyName: 'Riverside Tower', code: 'RT-SFO-TEN', label: 'Tenant Access', status: 'Active', expiresAt: '2026-11-15', scans: 410 },
  { propertyName: 'Standalone Clinic', code: 'SC-SJC-PAT', label: 'Patient Check-in', status: 'Active', expiresAt: '2026-12-01', scans: 305 },
  { propertyName: 'Orion Complex', code: 'OC-CHI-STAFF', label: 'Staff Access', status: 'Revoked', expiresAt: '2026-06-01', scans: 92 },
]

const propertyCodes = codeDefs.map((c, i) => {
  const prop = propertyByName[c.propertyName]
  return {
    id: `pc-${pad(i + 1)}`,
    propertyId: prop.id,
    propertyName: prop.name,
    code: c.code,
    label: c.label,
    status: c.status,
    expiresAt: c.expiresAt,
  }
})

const codeUsage = codeDefs.map((c, i) => {
  const pc = propertyCodes[i]
  const devices = Math.max(8, Math.round(c.scans * (c.status === 'Expired' || c.status === 'Revoked' ? 0.48 : 0.66)))
  const lastUsed =
    c.status === 'Expired'
      ? '2025-12-30 21:10'
      : c.status === 'Revoked'
        ? '2026-05-28 09:00'
        : c.scans < 100
          ? '2026-09-03 18:05'
          : `2026-09-04 0${6 + (i % 2)}:${String(10 + (i * 7) % 50).padStart(2, '0')}`
  return {
    id: `cu-${pad(i + 1)}`,
    propertyCodeId: pc.id,
    propertyId: pc.propertyId,
    code: pc.code,
    propertyName: pc.propertyName,
    scans: c.scans,
    uniqueDevices: devices,
    lastUsed,
  }
})

/* â”€â”€â”€ Downloads / sessions â”€â”€â”€ */
const mapDownloads = []
let dlN = 1
for (const prop of siteProperties) {
  const ver = currentVersion(prop.name)
  if (!ver) continue
  const readiness = prop.readiness
  const base = Math.round(180 + readiness * 55)
  const platforms =
    ver.status === 'Live'
      ? ['iOS', 'Android']
      : ver.status === 'Staging'
        ? prop.name.includes('Civic')
          ? ['Android']
          : prop.name.includes('Meridian')
            ? ['iOS']
            : ['iOS', 'Android']
        : prop.name.includes('Clinic')
          ? ['Android']
          : ['iOS']
  platforms.forEach((platform, pi) => {
    mapDownloads.push({
      id: `dl-${pad(dlN++)}`,
      propertyId: prop.id,
      propertyName: prop.name,
      mapVersionId: ver.id,
      platform,
      version: ver.version,
      downloads: Math.round(base * (platform === 'iOS' ? 1.12 : 0.94) * (0.85 + pi * 0.05)),
      lastSync: `2026-09-0${ver.status === 'Live' ? 4 : 3} 0${5 + (dlN % 3)}:${String((dlN * 11) % 60).padStart(2, '0')}`,
    })
  })
}

const sessionProfile = {
  'Orion Complex': ['Visitor', 'Staff'],
  'Harbor Mall Campus': ['Staff', 'Visitor'],
  'Summit Medical Campus': ['Patient', 'Staff'],
  'Northgate Plaza': ['Tenant', 'Visitor'],
  'Meridian Residences': ['Resident', 'Guest'],
  'Civic Center Annex': ['Visitor'],
  'Lakeside Community': ['Resident'],
  'Riverside Tower': ['Tenant'],
  'Standalone Clinic': ['Patient'],
}

const mobileSessions = []
let msN = 1
const sessionStatuses = ['Active', 'Active', 'Idle', 'Ended', 'Active']
for (const prop of siteProperties) {
  const labels = sessionProfile[prop.name] || ['Visitor']
  labels.forEach((userLabel, i) => {
    const platform = (msN + i) % 2 === 0 ? 'iOS' : 'AND'
    mobileSessions.push({
      id: `ms-${pad(msN)}`,
      propertyId: prop.id,
      propertyName: prop.name,
      deviceId: `${platform}-${(msN * 1117).toString(16).slice(-6).toUpperCase()}`,
      userLabel,
      startedAt: `2026-09-0${userLabel === 'Resident' && prop.name === 'Lakeside Community' ? 3 : 4} 0${5 + ((msN + i) % 3)}:${String((msN * 13) % 60).padStart(2, '0')}`,
      status: sessionStatuses[(msN - 1) % sessionStatuses.length],
    })
    msN += 1
  })
}

/* â”€â”€â”€ Analytics â”€â”€â”€ */
const journeys = routes.map((route, i) => {
  const def = routeDefs[i]
  const baseSessions = Math.round(80 + def.traffic * 520 * (route.status === 'Draft' ? 0.15 : 1))
  const completionRate =
    route.status === 'Draft' ? Math.round(55 + def.traffic * 20) : Math.round(82 + def.traffic * 10)
  return {
    id: `jn-${pad(i + 1)}`,
    propertyId: route.propertyId,
    propertyName: route.propertyName,
    routeId: route.id,
    routeName: route.name,
    sessions: baseSessions,
    completionRate: Math.min(98, completionRate),
    avgDurationMin:
      route.status === 'Draft'
        ? Math.round((route.avgDurationMin || 4) * 10 + 8) / 10
        : Math.round((route.avgDurationMin + 0.3) * 10) / 10,
  }
})

const dwellDefs = [
  { propertyName: 'Harbor Mall Campus', zone: 'Food Court', avgDwellMin: 18.4, visits: 890, peakHour: '12:00' },
  { propertyName: 'Orion Complex', zone: 'Main Lobby', avgDwellMin: 3.2, visits: 2100, peakHour: '08:30' },
  { propertyName: 'Summit Medical Campus', zone: 'Waiting Area B', avgDwellMin: 22.6, visits: 540, peakHour: '10:00' },
  { propertyName: 'Northgate Plaza', zone: 'Atrium', avgDwellMin: 5.8, visits: 620, peakHour: '17:00' },
  { propertyName: 'Meridian Residences', zone: 'Amenity Level Pool', avgDwellMin: 41.0, visits: 380, peakHour: '16:00' },
  { propertyName: 'Civic Center Annex', zone: 'Public Lobby', avgDwellMin: 9.5, visits: 410, peakHour: '09:00' },
  { propertyName: 'Harbor Mall Campus', zone: 'Cinema Lobby', avgDwellMin: 12.1, visits: 670, peakHour: '19:30' },
  { propertyName: 'Orion Complex', zone: 'Cafe Orion', avgDwellMin: 14.8, visits: 450, peakHour: '12:30' },
  { propertyName: 'Summit Medical Campus', zone: 'ER Entry', avgDwellMin: 7.4, visits: 980, peakHour: '11:00' },
  { propertyName: 'Lakeside Community', zone: 'Fitness Center', avgDwellMin: 36.2, visits: 210, peakHour: '07:00' },
  { propertyName: 'Riverside Tower', zone: 'Ground Lobby', avgDwellMin: 2.8, visits: 560, peakHour: '08:45' },
  { propertyName: 'Standalone Clinic', zone: 'Reception Desk', avgDwellMin: 11.3, visits: 290, peakHour: '09:30' },
]

const dwellMetrics = dwellDefs.map((d, i) => {
  const prop = propertyByName[d.propertyName]
  const loc = findLoc(d.propertyName, d.zone)
  if (!loc) throw new Error(`Dwell zone missing: ${d.propertyName} / ${d.zone}`)
  return {
    id: `dw-${pad(i + 1)}`,
    propertyId: prop.id,
    propertyName: prop.name,
    locationId: loc.id,
    zone: loc.name,
    avgDwellMin: d.avgDwellMin,
    visits: d.visits,
    peakHour: d.peakHour,
  }
})

const tourDefs = [
  { propertyName: 'Harbor Mall Campus', tourName: 'Retail Highlights', starts: 420, completions: 312, avgSteps: 8 },
  { propertyName: 'Orion Complex', tourName: 'Tenant Orientation', starts: 156, completions: 140, avgSteps: 6 },
  { propertyName: 'Summit Medical Campus', tourName: 'Outpatient Guide', starts: 890, completions: 802, avgSteps: 12 },
  { propertyName: 'Northgate Plaza', tourName: 'New Tenant Walkthrough', starts: 64, completions: 58, avgSteps: 5 },
  { propertyName: 'Meridian Residences', tourName: 'Amenity Tour', starts: 210, completions: 188, avgSteps: 7 },
  { propertyName: 'Civic Center Annex', tourName: 'Public Services Path', starts: 130, completions: 97, avgSteps: 9 },
  { propertyName: 'Lakeside Community', tourName: 'Resident Welcome', starts: 48, completions: 31, avgSteps: 6 },
  { propertyName: 'Riverside Tower', tourName: 'Executive Floor Intro', starts: 72, completions: 65, avgSteps: 5 },
  { propertyName: 'Standalone Clinic', tourName: 'First Visit Guide', starts: 190, completions: 176, avgSteps: 4 },
  { propertyName: 'Harbor Mall Campus', tourName: 'Cinema Night Path', starts: 340, completions: 290, avgSteps: 10 },
  { propertyName: 'Orion Complex', tourName: 'South Tower Day One', starts: 88, completions: 79, avgSteps: 7 },
  { propertyName: 'Summit Medical Campus', tourName: 'ER to Imaging', starts: 510, completions: 470, avgSteps: 11 },
]

const tours = tourDefs.map((t, i) => {
  const prop = propertyByName[t.propertyName]
  return { id: `tr-${pad(i + 1)}`, propertyId: prop.id, propertyName: prop.name, tourName: t.tourName, starts: t.starts, completions: t.completions, avgSteps: t.avgSteps }
})

const tenantDefs = [
  { propertyName: 'Orion Complex', tenant: 'Apex Legal', visits: 1240, lastVisit: '2026-09-04 07:10', topDestination: 'Suite 2201' },
  { propertyName: 'Harbor Mall Campus', tenant: 'Coastal Outfitters', visits: 3420, lastVisit: '2026-09-04 07:05', topDestination: 'Anchor Store 204' },
  { propertyName: 'Northgate Plaza', tenant: 'Blue Finch Cafe', visits: 890, lastVisit: '2026-09-03 20:30', topDestination: 'Unit 412' },
  { propertyName: 'Meridian Residences', tenant: 'Resident Pool', visits: 560, lastVisit: '2026-09-04 06:00', topDestination: 'Amenity Level Pool' },
  { propertyName: 'Orion Complex', tenant: 'Northwind Capital', visits: 980, lastVisit: '2026-09-04 07:22', topDestination: 'Suite 1601' },
  { propertyName: 'Summit Medical Campus', tenant: 'Imaging Partners', visits: 1560, lastVisit: '2026-09-04 07:35', topDestination: 'Radiology' },
  { propertyName: 'Harbor Mall Campus', tenant: 'Seaport Cinema', visits: 2100, lastVisit: '2026-09-04 00:15', topDestination: 'Cinema Lobby' },
  { propertyName: 'Civic Center Annex', tenant: 'City Clerk Office', visits: 640, lastVisit: '2026-09-03 16:40', topDestination: 'Permit Counter' },
  { propertyName: 'Lakeside Community', tenant: 'Building A HOA', visits: 210, lastVisit: '2026-09-03 19:10', topDestination: 'Fitness Center' },
  { propertyName: 'Riverside Tower', tenant: 'Pacific Advisors', visits: 720, lastVisit: '2026-09-04 06:55', topDestination: 'Suite 801' },
  { propertyName: 'Standalone Clinic', tenant: 'Bay Area Clinics LLC', visits: 430, lastVisit: '2026-09-04 07:18', topDestination: 'Exam 1' },
  { propertyName: 'Meridian Residences', tenant: 'Tower 1 HOA', visits: 390, lastVisit: '2026-09-04 05:40', topDestination: 'Residence 1408' },
  { propertyName: 'Northgate Plaza', tenant: 'Unit 110 Retail', visits: 510, lastVisit: '2026-09-04 07:00', topDestination: 'Unit 110' },
  { propertyName: 'Summit Medical Campus', tenant: 'Outpatient Clinics', visits: 1880, lastVisit: '2026-09-04 07:42', topDestination: 'Exam 312' },
]

const tenantActivity = tenantDefs.map((t, i) => {
  const prop = propertyByName[t.propertyName]
  const loc = findLoc(t.propertyName, t.topDestination)
  if (!loc) throw new Error(`Tenant destination missing: ${t.propertyName} / ${t.topDestination}`)
  return {
    id: `ta-${pad(i + 1)}`,
    propertyId: prop.id,
    propertyName: prop.name,
    tenant: t.tenant,
    visits: t.visits,
    lastVisit: t.lastVisit,
    topDestinationLocationId: loc.id,
    topDestination: loc.name,
  }
})

/* â”€â”€â”€ API / ops â”€â”€â”€ */
const apiClientSeeds = [
  { id: 'ac-001', name: 'Orion Mobile App', org: 'Orion Property Group', environment: 'Production', createdAt: '2025-03-12', status: 'Active' },
  { id: 'ac-002', name: 'Harbor POS Integration', org: 'Harbor Retail Holdings', environment: 'Production', createdAt: '2025-06-01', status: 'Active' },
  { id: 'ac-003', name: 'Summit Wayfinding', org: 'Summit Health Systems', environment: 'Production', createdAt: '2025-01-20', status: 'Active' },
  { id: 'ac-004', name: 'Atlas Dev Sandbox', org: 'Atlas Ventures', environment: 'Development', createdAt: '2026-07-15', status: 'Active' },
  { id: 'ac-005', name: 'Legacy Sync Service', org: 'Northgate Management Co.', environment: 'Staging', createdAt: '2024-11-08', status: 'Disabled' },
  { id: 'ac-006', name: 'Meridian Resident App', org: 'Coastal Retail Partners', environment: 'Production', createdAt: '2025-09-04', status: 'Active' },
  { id: 'ac-007', name: 'Civic Services Portal', org: 'City of Portland', environment: 'Production', createdAt: '2026-02-11', status: 'Active' },
  { id: 'ac-008', name: 'Clinic Check-in Kiosk', org: 'Bay Area Clinics LLC', environment: 'Production', createdAt: '2026-04-22', status: 'Active' },
]

const apiClients = apiClientSeeds.map((c) => ({
  ...c,
  organizationId: orgByName[c.org].id,
}))

const apiClientByName = Object.fromEntries(apiClients.map((c) => [c.name, c]))

const apiKeys = [
  { id: 'ak-001', clientName: 'Orion Mobile App', prefix: 'keiros_live_ot_', scopes: 'maps:read, routes:read', lastUsed: '2026-09-04 07:32', status: 'Active' },
  { id: 'ak-002', clientName: 'Harbor POS Integration', prefix: 'keiros_live_hm_', scopes: 'locations:read, analytics:read', lastUsed: '2026-09-04 06:58', status: 'Active' },
  { id: 'ak-003', clientName: 'Summit Wayfinding', prefix: 'keiros_live_smc_', scopes: 'maps:read, routes:read, codes:read', lastUsed: '2026-09-04 07:20', status: 'Active' },
  { id: 'ak-004', clientName: 'Atlas Dev Sandbox', prefix: 'keiros_dev_atl_', scopes: 'maps:read', lastUsed: '2026-09-03 21:14', status: 'Active' },
  { id: 'ak-005', clientName: 'Legacy Sync Service', prefix: 'keiros_stg_ng_', scopes: 'maps:read, locations:read', lastUsed: '2026-08-12 10:00', status: 'Revoked' },
  { id: 'ak-006', clientName: 'Meridian Resident App', prefix: 'keiros_live_mr_', scopes: 'maps:read, routes:read, codes:read', lastUsed: '2026-09-04 07:41', status: 'Active' },
  { id: 'ak-007', clientName: 'Civic Services Portal', prefix: 'keiros_live_cca_', scopes: 'maps:read, locations:read', lastUsed: '2026-09-04 07:05', status: 'Active' },
  { id: 'ak-008', clientName: 'Clinic Check-in Kiosk', prefix: 'keiros_live_sc_', scopes: 'maps:read, codes:read', lastUsed: '2026-09-04 07:19', status: 'Rotated' },
].map((k) => ({ ...k, apiClientId: apiClientByName[k.clientName].id }))

const apiUsageStats = [
  { id: 'au-001', clientName: 'Orion Mobile App', endpoint: '/v1/maps/live', requests: 98200, errors: 41, p95Ms: 95 },
  { id: 'au-002', clientName: 'Harbor POS Integration', endpoint: '/v1/locations', requests: 12400, errors: 3, p95Ms: 62 },
  { id: 'au-003', clientName: 'Summit Wayfinding', endpoint: '/v1/routes/compute', requests: 45600, errors: 28, p95Ms: 120 },
  { id: 'au-004', clientName: 'Atlas Dev Sandbox', endpoint: '/v1/maps/preview', requests: 1800, errors: 12, p95Ms: 140 },
  { id: 'au-005', clientName: 'Meridian Resident App', endpoint: '/v1/routes/compute', requests: 22100, errors: 9, p95Ms: 110 },
  { id: 'au-006', clientName: 'Civic Services Portal', endpoint: '/v1/locations', requests: 8600, errors: 5, p95Ms: 78 },
  { id: 'au-007', clientName: 'Clinic Check-in Kiosk', endpoint: '/v1/codes/validate', requests: 5400, errors: 2, p95Ms: 48 },
  { id: 'au-008', clientName: 'Legacy Sync Service', endpoint: '/v1/maps/export', requests: 920, errors: 180, p95Ms: 420 },
  { id: 'au-009', clientName: 'Orion Mobile App', endpoint: `/v1/routes/${routes[0].id}`, requests: 31200, errors: 11, p95Ms: 88 },
  { id: 'au-010', clientName: 'Summit Wayfinding', endpoint: '/v1/maps/live', requests: 27800, errors: 7, p95Ms: 102 },
].map((u) => ({ ...u, apiClientId: apiClientByName[u.clientName].id }))

const apiLogs = [
  { id: 'al-001', timestamp: '2026-09-04 07:32:10', clientName: 'Orion Mobile App', method: 'GET', path: '/v1/maps/live', status: 200, durationMs: 82 },
  { id: 'al-002', timestamp: '2026-09-04 07:31:55', clientName: 'Summit Wayfinding', method: 'POST', path: '/v1/routes/compute', status: 200, durationMs: 118 },
  { id: 'al-003', timestamp: '2026-09-04 07:31:40', clientName: 'Harbor POS Integration', method: 'GET', path: '/v1/locations', status: 200, durationMs: 58 },
  { id: 'al-004', timestamp: '2026-09-04 07:30:22', clientName: 'Atlas Dev Sandbox', method: 'GET', path: '/v1/maps/preview', status: 429, durationMs: 12 },
  { id: 'al-005', timestamp: '2026-09-04 07:29:08', clientName: 'Orion Mobile App', method: 'GET', path: `/v1/routes/${routes[0].id}`, status: 200, durationMs: 45 },
  { id: 'al-006', timestamp: '2026-09-04 07:28:51', clientName: 'Meridian Resident App', method: 'POST', path: '/v1/routes/compute', status: 200, durationMs: 104 },
  { id: 'al-007', timestamp: '2026-09-04 07:27:33', clientName: 'Clinic Check-in Kiosk', method: 'POST', path: '/v1/codes/validate', status: 200, durationMs: 36 },
  { id: 'al-008', timestamp: '2026-09-04 07:26:14', clientName: 'Civic Services Portal', method: 'GET', path: '/v1/locations', status: 200, durationMs: 71 },
  { id: 'al-009', timestamp: '2026-09-04 07:24:02', clientName: 'Legacy Sync Service', method: 'GET', path: '/v1/maps/export', status: 503, durationMs: 1800 },
  { id: 'al-010', timestamp: '2026-09-04 07:22:48', clientName: 'Summit Wayfinding', method: 'GET', path: '/v1/maps/live', status: 200, durationMs: 97 },
  { id: 'al-011', timestamp: '2026-09-04 07:21:05', clientName: 'Harbor POS Integration', method: 'GET', path: '/v1/analytics/dwell', status: 200, durationMs: 133 },
  { id: 'al-012', timestamp: '2026-09-04 07:19:40', clientName: 'Meridian Resident App', method: 'GET', path: `/v1/codes/${propertyCodes.find((c) => c.propertyName === 'Meridian Residences').code}`, status: 200, durationMs: 41 },
].map((l) => ({ ...l, apiClientId: apiClientByName[l.clientName].id }))

const systemHealthServices = [
  { id: 'sh-001', name: 'API Gateway', health: 'Healthy', latencyMs: 42, uptimePct: 99.98 },
  { id: 'sh-002', name: 'Map Rendering', health: 'Healthy', latencyMs: 118, uptimePct: 99.92 },
  { id: 'sh-003', name: 'Mobile Sync', health: 'Degraded', latencyMs: 340, uptimePct: 98.4 },
  { id: 'sh-004', name: 'Analytics Pipeline', health: 'Healthy', latencyMs: 86, uptimePct: 99.95 },
  { id: 'sh-005', name: 'Auth Service', health: 'Healthy', latencyMs: 28, uptimePct: 99.99 },
  { id: 'sh-006', name: 'Notification Bus', health: 'Down', latencyMs: 0, uptimePct: 94.2 },
]
const serviceByName = Object.fromEntries(systemHealthServices.map((s) => [s.name, s]))

const orionLive = currentVersion('Orion Complex')
const alerts = [
  { id: 'alrt-001', title: 'Mobile Sync latency elevated', source: 'Mobile Sync', serviceId: serviceByName['Mobile Sync'].id, severity: 'Warning', triggeredAt: '2026-09-04 07:05', acknowledged: false },
  { id: 'alrt-002', title: 'Notification Bus unreachable', source: 'Notification Bus', serviceId: serviceByName['Notification Bus'].id, severity: 'Critical', triggeredAt: '2026-09-04 06:48', acknowledged: false },
  { id: 'alrt-003', title: `Map publish succeeded â€” Orion ${orionLive?.version ?? 'v5.1.2'}`, source: 'Map Publishing', serviceId: null, severity: 'Info', triggeredAt: '2026-08-29 16:40', acknowledged: true },
  { id: 'alrt-004', title: `GPS drift â€” Civic ${realFloorLabel('Civic Center Annex', 'L02')} entry`, source: 'Mapping Quality', serviceId: null, severity: 'Critical', triggeredAt: '2026-09-04 05:12', acknowledged: false },
  { id: 'alrt-005', title: 'API rate limit â€” Atlas sandbox', source: 'API Gateway', serviceId: serviceByName['API Gateway'].id, severity: 'Warning', triggeredAt: '2026-09-04 07:30', acknowledged: true },
  { id: 'alrt-006', title: 'Legacy Sync 503 spike', source: 'API Gateway', serviceId: serviceByName['API Gateway'].id, severity: 'Warning', triggeredAt: '2026-09-04 07:24', acknowledged: false },
  { id: 'alrt-007', title: 'Harbor L02 mapping blocked on correction', source: 'Field Mapping', serviceId: null, severity: 'Info', triggeredAt: '2026-09-03 18:20', acknowledged: true },
  { id: 'alrt-008', title: 'ER entry beacon timeout', source: 'Mapping Quality', serviceId: null, severity: 'Critical', triggeredAt: '2026-09-04 07:00', acknowledged: false },
]

const lakesideVer = currentVersion('Lakeside Community')
const meridianVer = currentVersion('Meridian Residences')
const civicVer = currentVersion('Civic Center Annex')
const auditLogs = [
  { id: 'aud-001', timestamp: '2026-09-04 07:32:18', actor: 'Sarah Chen', action: 'Acknowledged alert', target: 'API rate limit â€” Atlas sandbox', ip: '10.0.0.12' },
  { id: 'aud-002', timestamp: '2026-09-04 06:55:03', actor: 'Marcus Webb', action: 'Updated property', target: 'Orion Complex', ip: '192.168.4.18' },
  { id: 'aud-003', timestamp: '2026-09-04 06:30:47', actor: 'Priya Nair', action: 'Rejected approval', target: `Lakeside Community ${lakesideVer?.version ?? 'v0.3.0'}`, ip: '10.0.1.55' },
  { id: 'aud-004', timestamp: '2026-09-03 22:10:22', actor: 'Devon Mills', action: 'Rotated API key', target: 'Clinic Check-in Kiosk', ip: '203.0.113.88' },
  { id: 'aud-005', timestamp: '2026-09-03 16:42:01', actor: 'James Okonkwo', action: 'Submitted correction', target: 'Harbor Mall Campus â€” Anchor Store 204', ip: '10.0.2.19' },
  { id: 'aud-006', timestamp: '2026-09-04 07:18:44', actor: 'Rita Gomez', action: 'Submitted map version', target: `Meridian Residences ${meridianVer?.version ?? 'v1.2.0'}`, ip: '10.0.2.44' },
  { id: 'aud-007', timestamp: '2026-09-04 07:11:09', actor: 'Noah Kim', action: 'Completed mapping task', target: `Summit Medical Campus ${realFloorLabel('Summit Medical Campus', 'L02')}`, ip: '10.0.2.51' },
  { id: 'aud-008', timestamp: '2026-09-04 06:40:22', actor: 'Aisha Rahman', action: 'Generated property code', target: propertyCodes.find((c) => c.propertyName === 'Meridian Residences').code, ip: '198.51.100.22' },
  { id: 'aud-009', timestamp: '2026-09-03 14:05:11', actor: 'Mei Lin', action: 'Opened quality issue', target: 'Harbor Mall Campus L01 elevation', ip: '10.0.1.60' },
  { id: 'aud-010', timestamp: '2026-09-03 11:28:50', actor: 'Chris Delgado', action: 'Updated route draft', target: routes.find((r) => r.id === 'rt-005').name, ip: '203.0.113.40' },
  { id: 'aud-011', timestamp: '2026-09-02 09:15:00', actor: 'Rita Gomez', action: 'Submitted approval', target: `Civic Center Annex ${civicVer?.version ?? 'v1.8.0'}`, ip: '10.0.2.44' },
  { id: 'aud-012', timestamp: '2026-09-01 17:02:33', actor: 'Hank Ortega', action: 'Disabled API client', target: 'Legacy Sync Service', ip: '10.0.0.8' },
].map((a) => ({
  ...a,
  actorUserId: userByName(a.actor)?.id ?? null,
}))

const dashboardKpis = {
  properties: complexes.length,
  published: complexes.filter((p) => p.status === 'Published').length,
  inReview: complexes.filter((p) => p.status === 'Review').length,
  avgReadiness: Math.round(complexes.reduce((s, p) => s + p.readiness, 0) / complexes.length),
  activeUsers: users.filter((u) => u.status === 'Active').length,
  pendingApprovals: approvals.filter((a) => a.status === 'Pending').length,
  openCorrections: corrections.filter((c) => c.status !== 'Resolved').length,
  activeSessions: mobileSessions.filter((s) => s.status === 'Active').length,
  siteProperties: siteProperties.length,
}

/* â”€â”€â”€ FK validation â”€â”€â”€ */
const errors = []
const propIds = new Set(siteProperties.map((p) => p.id))
const locIds = new Set(locations.map((l) => l.id))
const floorIds = new Set(floors.map((f) => f.id))
const userIds = new Set(users.map((u) => u.id))
const mvIds = new Set(mapVersions.map((v) => v.id))
const routeIds = new Set(routes.map((r) => r.id))
const pcIds = new Set(propertyCodes.map((c) => c.id))
const clientIds = new Set(apiClients.map((c) => c.id))

for (const l of locations) if (!propIds.has(l.propertyId)) errors.push(`Location ${l.id} bad propertyId`)
for (const f of floors) if (!propIds.has(f.propertyId)) errors.push(`Floor ${f.id} bad propertyId`)
for (const r of routes) {
  if (!propIds.has(r.propertyId)) errors.push(`Route ${r.id} bad propertyId`)
  if (!locIds.has(r.fromLocationId) || !locIds.has(r.toLocationId)) errors.push(`Route ${r.id} bad location FK`)
}
for (const j of journeys) {
  if (!routeIds.has(j.routeId)) errors.push(`Journey ${j.id} bad routeId`)
  if (j.propertyId !== routes.find((r) => r.id === j.routeId)?.propertyId) errors.push(`Journey ${j.id} property/route mismatch`)
}
for (const u of codeUsage) {
  if (!pcIds.has(u.propertyCodeId)) errors.push(`Usage ${u.id} bad propertyCodeId`)
}
for (const d of mapDownloads) {
  if (!mvIds.has(d.mapVersionId)) errors.push(`Download ${d.id} bad mapVersionId`)
}
for (const a of approvals) {
  if (!mvIds.has(a.mapVersionId)) errors.push(`Approval ${a.id} bad mapVersionId`)
  if (!userIds.has(a.submittedByUserId)) errors.push(`Approval ${a.id} bad user`)
}
for (const c of corrections) {
  if (!locIds.has(c.locationId)) errors.push(`Correction ${c.id} bad locationId`)
}
for (const q of mappingQueue) {
  if (!floorIds.has(q.floorId)) errors.push(`Queue ${q.id} bad floorId`)
}
for (const d of dwellMetrics) {
  if (!locIds.has(d.locationId)) errors.push(`Dwell ${d.id} bad locationId`)
}
for (const t of tenantActivity) {
  if (!locIds.has(t.topDestinationLocationId)) errors.push(`Tenant ${t.id} bad locationId`)
}
for (const u of users) {
  if (!organizations.some((o) => o.id === u.organizationId)) errors.push(`User ${u.id} bad org`)
  if (!roles.some((r) => r.id === u.roleId)) errors.push(`User ${u.id} bad role`)
}
for (const k of apiKeys) {
  if (!clientIds.has(k.apiClientId)) errors.push(`Key ${k.id} bad client`)
}
if (errors.length) {
  console.error('Correlation errors:\n' + errors.join('\n'))
  process.exit(1)
}

function dumpArr(name, type, value) {
  return `export const ${name}: ${type}[] = ${JSON.stringify(value, null, 2)}\n`
}

let body = typesBlock + '\n'
body += dumpArr('complexes', 'Complex', complexes)
body += `\n/** Dashboard portfolio (= complexes). Ops joins use siteProperties. */\nexport const properties = complexes\n\n`
body += dumpArr('siteProperties', 'SiteProperty', siteProperties)
body += '\n'
body += `export const propertyLabels: string[] = ${JSON.stringify(propertyLabels, null, 2)}\n\n`
body += dumpArr('organizations', 'Organization', organizations)
body += '\n'
body += dumpArr('users', 'User', users)
body += '\n'
body += dumpArr('roles', 'Role', roles)
body += '\n'
body += dumpArr('buildings', 'Building', buildings)
body += '\n'
body += dumpArr('floors', 'Floor', floors)
body += '\n'
body += dumpArr('locations', 'MapLocation', locations)
body += '\n'
body += dumpArr('mappingQueue', 'MappingQueueItem', mappingQueue)
body += '\n'
body += dumpArr('qualityIssues', 'QualityIssue', qualityIssues)
body += '\n'
body += dumpArr('approvals', 'Approval', approvals)
body += '\n'
body += dumpArr('corrections', 'Correction', corrections)
body += '\n'
body += dumpArr('mapVersions', 'MapVersion', mapVersions)
body += '\n'
body += dumpArr('routes', 'Route', routes)
body += '\n'
body += dumpArr('propertyCodes', 'PropertyCode', propertyCodes)
body += '\n'
body += dumpArr('codeUsage', 'CodeUsage', codeUsage)
body += '\n'
body += dumpArr('mapDownloads', 'MapDownload', mapDownloads)
body += '\n'
body += dumpArr('mobileSessions', 'MobileSession', mobileSessions)
body += '\n'
body += dumpArr('journeys', 'Journey', journeys)
body += '\n'
body += dumpArr('dwellMetrics', 'DwellMetric', dwellMetrics)
body += '\n'
body += dumpArr('tours', 'Tour', tours)
body += '\n'
body += dumpArr('tenantActivity', 'TenantActivity', tenantActivity)
body += '\n'
body += dumpArr('apiClients', 'ApiClient', apiClients)
body += '\n'
body += dumpArr('apiKeys', 'ApiKey', apiKeys)
body += '\n'
body += dumpArr('apiUsageStats', 'ApiUsageStat', apiUsageStats)
body += '\n'
body += dumpArr('apiLogs', 'ApiLog', apiLogs)
body += '\n'
body += dumpArr('alerts', 'Alert', alerts)
body += '\n'
body += dumpArr('auditLogs', 'AuditLog', auditLogs)
body += '\n'
body += dumpArr('systemHealthServices', 'SystemHealthService', systemHealthServices)
body += '\n'
body += `export const dashboardKpis = ${JSON.stringify(dashboardKpis, null, 2)}\n`

fs.writeFileSync(outPath, body, 'utf8')
console.log('Wrote', outPath)
console.log({
  complexes: complexes.length,
  siteProperties: siteProperties.length,
  buildings: buildings.length,
  floors: floors.length,
  locations: locations.length,
  routes: routes.length,
  propertyCodes: propertyCodes.length,
  users: users.length,
  orgs: organizations.length,
  correlationErrors: 0,
})

