/** Firestore collection names (must match DeployCDCI/config/collections.json) */
export const COLLECTIONS = {
  organizations: 'organizations',
  roles: 'roles',
  users: 'users',
  complexes: 'complexes',
  siteProperties: 'site_properties',
  buildings: 'buildings',
  floors: 'floors',
  locations: 'locations',
  mappingQueue: 'mapping_queue',
  qualityIssues: 'quality_issues',
  approvals: 'approvals',
  corrections: 'corrections',
  mapVersions: 'map_versions',
  routes: 'routes',
  propertyCodes: 'property_codes',
  codeUsage: 'code_usage',
  mapDownloads: 'map_downloads',
  mobileSessions: 'mobile_sessions',
  journeys: 'journeys',
  dwellMetrics: 'dwell_metrics',
  tours: 'tours',
  tenantActivity: 'tenant_activity',
  apiClients: 'api_clients',
  apiKeys: 'api_keys',
  apiUsageStats: 'api_usage_stats',
  apiLogs: 'api_logs',
  navigationSessions: 'navigation_sessions',
  alerts: 'alerts',
  auditLogs: 'audit_logs',
  systemHealthServices: 'system_health_services',
  dashboardKpis: 'dashboard_kpis',
  meta: '_meta',
} as const
